title: Trevor Andrus # your name (or website title) here
logo: "/images/Andrus (355) 2.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  - Course Developer _Brigham Young University Statistics Department_
  - BS in Data Science (April 2022)
  - Minor in Economics (April 2022)
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/trevor-andrus/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
