title: Trevor Andrus # your name (or website title) here
logo: "/images/IMG-5165.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Currently working as a teaching assistant and course developer at Brigham Young University while persuing an undergraduate degree in statistics.
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/trevor-andrus/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
